apiVersion: v1
entries:
  fabricrealtime:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T17:08:17.139388-07:00
    description: A Helm chart for DOS Realtime
    digest: bf98e0869f0036d9afacf0aefe51f33108d57fe90c34c067198dd0f6a4b67f8e
    name: fabricrealtime
    urls:
    - https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/helm/releases/fabricrealtime-0.1.1.tgz
    version: 0.1.1
  loadbalancer:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T17:08:17.1403865-07:00
    description: A Helm chart for DOS Load balancer
    digest: 0386e1c864d26b179c82ec385ce541c4da9d39d4638f5d01c2a479d2facc5ea0
    name: loadbalancer
    urls:
    - https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/helm/releases/loadbalancer-0.1.0.tgz
    version: 0.1.0
generated: 2018-09-24T17:08:17.1373889-07:00
