apiVersion: v1
entries:
  dos.realtime:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T14:07:15.8805123-07:00
    description: A Helm chart for DOS Realtime
    digest: 143b4a70c82f7c6f9feef4ef91566c4a27d6a5b8aee5b3f877954d009b5355eb
    name: dos.realtime
    urls:
    - https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/helm/releases/dos.realtime-0.1.1.tgz
    version: 0.1.1
generated: 2018-09-24T14:07:15.8795022-07:00
