apiVersion: v1
entries:
  fabricrealtime:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T14:48:16.7695392-07:00
    description: A Helm chart for DOS Realtime
    digest: bf98e0869f0036d9afacf0aefe51f33108d57fe90c34c067198dd0f6a4b67f8e
    name: fabricrealtime
    urls:
    - https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/helm/releases/fabricrealtime-0.1.1.tgz
    version: 0.1.1
generated: 2018-09-24T14:48:16.7675449-07:00
