kind: CronJob #Set as a cronjob to enable automatic restarting of the pod to clear the jobserver memory. See nlp.patientsafety.regenstrief issue #8
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.jobserver
  namespace: fabricnlp    
  labels:
    app: jobserver
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 86400 
      template:
        spec:
          containers:
            - name: jobserver
              image: healthcatalyst/fabric.nlp.docker.jobs:1
              imagePullPolicy: Always          
              env:
                - name: NLPWEB_EXTERNAL_URL
                  valueFrom:
                    secretKeyRef:
                      name: nlpweb-external-url
                      key: value
                - name: JOBSERVER_EXTERNAL_URL
                  valueFrom:
                    secretKeyRef:
                      name: jobserver-external-url
                      key: value
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysqlpassword
                      key: password
              ports:
                - containerPort: 8084
                  name: jobserver
              # livenessProbe:
              #   httpGet:
              #     path: /nlp
              #     port: 8084
              #   initialDelaySeconds: 60
              #   periodSeconds: 60
              volumeMounts:
                - name: jobs-persistent-storage
                  mountPath: /opt/jobWork/
                  subPath: jobs
          restartPolicy: Always
          nodeSelector:
              joborsolr: job
          volumes:
          - name: jobs-persistent-storage
            persistentVolumeClaim:
              claimName: nlp.jobserver            
