kind: Service
apiVersion: v1
metadata:
  name: rserve-direct-port
  namespace: fabricmachinelearning
  annotations:
    # from https://radu-matei.com/blog/k8s-appsvc/
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: $INTERNALSUBNET$
  labels:
    dns: rserve    
    expose: internal
spec:
  selector:
    app: rserve
  ports:
  - name: rserveport
    protocol: TCP
    port: 6311
    targetPort: 6311
  type: LoadBalancer
---