kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{size}}
